name: Validating branch on Pull Request
on:
  pull_request:
    branches:
      - mainster
      - add-playwright-to-githubaction
jobs:
  install-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: install-dependencies
        run: yarn
  check-prettier:
    needs: install-dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - run: yarn fe prettier-check
      - name: send message
        if: ${{ failure() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#D22B2B"
          message: /${{ github.event.pull_request.head.ref }}/ prettier not pass 😢
  test:
    runs-on: ubuntu-20.04
    needs: check-prettier
    steps:
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: /${{ github.event.pull_request.head.ref }}/ Running test on branch
      - run: npx playwright install
      - run: yarn fe build
      - run: yarn fe start &
      - run: yarn fe-at playwright-test
      - uses: papeloto/action-zip@v1
        if: ${{ failure() }}
        with:
          files: packages/ntc-fe-automation-test/test-results
          dest: test-results.zip
      - name: send message
        if: ${{ failure() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#D22B2B"
          message: /${{ github.event.pull_request.head.ref }}/ Github action does not pass test 😢
          file: "test-results.zip"
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: my-artifact
          path: packages/ntc-fe-automation-test/test-results
